name: iOS Build Generation

on:
  workflow_dispatch: # يتيح لك تشغيل التحويل يدوياً بكبسة زر

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Xcode version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 'latest-stable'

    - name: Build App Specification
      run: |
        xcodebuild -project iOSStore/iOSStore.xcodeproj -scheme iOSStore -sdk iphoneos -configuration Release CODE_SIGNING_ALLOWED=NO

    - name: Create IPA Package
      run: |
        mkdir -p build/Payload
        mv build/Release-iphoneos/iOSStore.app build/Payload/
        cd build && zip -r iOSStore.ipa Payload

    - name: Upload IPA Artifact
      uses: actions/upload-artifact@v4
      with:
        name: iOSStore-Production-IPA
        path: build/iOSStore.ipa
